-- SnowTS DDL -- All table definitions
-- Replace {{DB}} with your database name and {{WH}} with your warehouse name before executing.
-- Execute these statements in order.

CREATE TABLE IF NOT EXISTS {{DB}}.APP.ARTICLES (
    ID TEXT NOT NULL PRIMARY KEY,
    TITLE TEXT,
    SLUG TEXT,
    FILE_PATH TEXT,
    CONTENT_HASH TEXT,
    SUMMARY TEXT,
    SOURCE_TYPE TEXT,
    RAW_SOURCE_PATH TEXT,
    CREATED_AT TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS {{DB}}.APP.ARTICLE_CONTENT (
    ID TEXT NOT NULL PRIMARY KEY,
    ARTICLE_ID TEXT,
    TITLE TEXT,
    CONTENT TEXT,
    SOURCE_TYPE TEXT,
    CLIENT_NAME TEXT,
    TAGS_TEXT TEXT
);

CREATE TABLE IF NOT EXISTS {{DB}}.APP.ARTICLE_REVISIONS (
    ID TEXT NOT NULL PRIMARY KEY,
    ARTICLE_ID TEXT,
    CONTENT_SNAPSHOT TEXT,
    CHANGE_REASON TEXT,
    CREATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS {{DB}}.APP.ARTICLE_LINKS (
    SOURCE_ARTICLE_ID TEXT,
    TARGET_ARTICLE_ID TEXT,
    LINK_TYPE TEXT
);

CREATE TABLE IF NOT EXISTS {{DB}}.APP.ARTICLE_TAGS (
    ARTICLE_ID TEXT,
    TAG_ID TEXT
);

CREATE TABLE IF NOT EXISTS {{DB}}.APP.CLIENTS (
    ID TEXT NOT NULL PRIMARY KEY,
    NAME TEXT,
    INDUSTRY TEXT,
    ENGAGEMENT_STATUS TEXT,
    SUMMARY TEXT,
    LAST_CONTACT DATE,
    CREATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS {{DB}}.APP.CLIENT_CONTACTS (
    ID TEXT NOT NULL PRIMARY KEY,
    CLIENT_ID TEXT,
    NAME TEXT,
    ROLE TEXT,
    EMAIL TEXT
);

CREATE TABLE IF NOT EXISTS {{DB}}.APP.TAGS (
    ID TEXT NOT NULL PRIMARY KEY,
    NAME TEXT,
    TAG_TYPE TEXT
);

CREATE TABLE IF NOT EXISTS {{DB}}.APP.TODOS (
    ID TEXT NOT NULL PRIMARY KEY,
    TITLE TEXT,
    DESCRIPTION TEXT,
    SOURCE_ARTICLE_ID TEXT,
    CLIENT_ID TEXT,
    STATUS TEXT,
    DUE_DATE DATE,
    PRIORITY TEXT,
    CREATED_AT TIMESTAMP_NTZ,
    TAGS_TEXT TEXT,
    GROUP_NAME TEXT,
    CONFIDENCE TEXT,
    SOURCE TEXT,
    REJECTED_AT TIMESTAMP_NTZ,
    ARCHIVED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS {{DB}}.APP.ANNOTATIONS (
    ID TEXT NOT NULL PRIMARY KEY,
    ARTICLE_ID TEXT,
    HIGHLIGHTED_TEXT TEXT,
    INSTRUCTION TEXT,
    AI_RESPONSE TEXT,
    STATUS TEXT,
    CREATED_AT TIMESTAMP_NTZ,
    PROCESSED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS {{DB}}.APP.PIPELINE_RUNS (
    ID TEXT NOT NULL PRIMARY KEY,
    PIPELINE_TYPE TEXT,
    STATUS TEXT,
    FILES_PROCESSED NUMBER,
    ERROR_LOG TEXT,
    STARTED_AT TIMESTAMP_NTZ,
    COMPLETED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS {{DB}}.APP.WIKI_ARTICLES (
    ID TEXT NOT NULL PRIMARY KEY,
    SLUG TEXT NOT NULL,
    TITLE TEXT NOT NULL,
    SUMMARY TEXT,
    CATEGORY TEXT,
    PARENT_TOPIC TEXT,
    SOURCE_ARTICLE_IDS TEXT,
    TAGS_TEXT TEXT,
    CREATED_AT TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS {{DB}}.APP.RAW_DOCS_STAGING (
    FILENAME TEXT,
    PARSED_CONTENT TEXT,
    DOC_TYPE TEXT,
    EXTRACTED_FIELDS VARIANT,
    TAGS VARIANT,
    WIKI_TOPICS VARIANT
);

CREATE STAGE IF NOT EXISTS {{DB}}.APP.RAW_DOCS DIRECTORY = (ENABLE = TRUE);
